<?php
// 3.2.5 - documentation-of added for languages requiring it
// for English is identical to documentation
// 3.2.6 - txtNoHosts
// 3.2.8 - phpNotExists - txtProjectsLink -	phpExtensions - phpVersionsUse
// 3.3.0 - txtPathNoSlash
// 3.3.2 - txtSlashEnd
// 3.3.7 - apacheLoadedModules

$langues = array(
	'langue' => 'Deutsch',
	'locale' => 'german',
	'titreHtml' => 'WAMPSERVER Homepage',
	'titreConf' => 'Server-Konfiguration',
	'versa' => 'Apache-Version:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/de/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/de/',
	'versp' => 'PHP-Version:',
	'server' => 'Server-Software:',
	'documentation' => 'Dokumentation',
	'documentation-of' => 'Dokumentation',
	'docp' => 'www.php.net/manual/de/',
	'versm' => 'MySQL-Version:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'MariaDB-Version: ',
	'docmaria' => 'mariadb.com/kb/de/mariadb/documentation',
	'phpExt' => 'Geladene Erweiterungen: ',
	'titrePage' => 'Werkzeuge',
	'txtProjet' => 'Projekte',
	'txtNoProjet' => 'Noch keine Projekte.<br />Um ein neues Projekt zu erstellen, einfach ein Verzeichnis in „www“ erstellen.',
	'txtProjects' => 'Ordner in %s<br />Um sie als HTTP-Link zu nutzen, muss erst ein VirtualHost erstellt werden.',
	'txtProjectsLink' =>'Es funktioniert auch: Rechtsklick, Einstellungen, Caution: Risky …, Allow links on projects …',
	'txtAlias' => 'Aktuelle Aliases',
	'txtNoAlias' => 'Bisher kein Alias.<br />Zum erstellen, das WAMPSERVER-Menü nutzen.',
	'txtVhost' => 'Aktuelle VirtualHosts',
	'txtServerName' => 'Server-Name %s hat einen Syntax-Fehler in Datei %s',
	'txtDocRoot' => 'Server-Name %s use DocumentRoot %s reserved to localhost',
	'txtTLDdev' => 'Server-Name %s use TLD %s which is monopolized by web browsers. Use another TLD (.test for example)',
	'txtNoHosts' => 'Server-Name %s ist nicht in der Host-Datei definiert.',
	'txtServerNameIp' => 'IP %s für Server-Name %s stimmt nicht mit Datei %s überein',
	'txtVhostNotClean' => 'Die Datei %s wurde nicht bereinigt. Es verbleiben Beispieldateien wie: dummy-host.example.com',
	'txtNoVhost' => 'Kein VirtualHost erstellt. Für jedes Projekt in Datei: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf hinzufügen',
	'txtNoIncVhost' => 'Auskommentieren oder hinzufügen von <i>Include conf/extra/httpd-vhosts.conf</i> in Datei wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Die Datei: %s existiert nicht',
	'txtNoPath' => 'Der Pfad %s für %s existiert nicht (Datei: %s)',
	'txtSlashEnd' => 'Der Pfad %s für %s wurde mit einem Schrägstrich beendet (Datei: %s)',
	'txtPathNoSlash' => 'Der Pfad %s für %s wurde nicht mit einem Schrägstrich / beendet (Datei: %s)',
	'txtNotWritable' => 'Die Datei: %s ist nicht beschreibbar',
	'txtNbNotEqual' => 'Die Anzahl von %s stimmt nicht mit der Anzahl von %s in Datei %s überein',
	'txtAddVhost' => 'Einen VirtualHost hinzufügen',
	'txtPortNumber' => 'Port-Nummer für %s hat einen falschen Wert oder ist nicht gleich Datei %s',
	'txtCorrected' => 'Einige VirtualHosts-Fehler konnten korrigiert werden.',
	'forum' => 'Wampserver-Forum',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Port definert für Apache: ',
	'mysqlportUsed' => 'Port definert für MySQL: ',
	'mariaportUsed' => 'Port definert für MariaDB: ',
	'defaultDBMS' => 'Standard DBMS',
	'phpNotExists' => 'PHP-Version existiert nicht',
	'HelpMySQLMariaDB' => 'How to use MySQL and/or MariaDB?<br>What is a default DBMS?<br>How to change the default DBMS?<br>Go to the related help: Right-click Wampmanager icon -> Help -> MariaDB - MySQL',
	'nolocalhost' => 'It\'s a bad idea to add localhost in the url of launching projects. It is best to define VirtualHost in<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />file and not add localhost in the url.',
	'phpExtensions' => 'Geladene PHP-Erweiterungen',
	'phpVersionsUse' => 'Nutzung der PHP-Versionen',
	'apacheLoadedModules' => 'Geladene Apache-Module',
	);
?>
